version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      args:
        REACT_APP_API_BASE_URL: http://backend:5001
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ../pettripflask
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db
    networks:
      - app-network

networks:
  app-network: